In [10]:
!pip install opencv-python numpy



In [14]:
import cv2
import numpy as np

# Load image
image = cv2.imread("sample.jpg")


# Print image shape
print("Image Shape:", image.shape)

# Print image dimensions
height, width, channels = image.shape
print("Height:", height)
print("Width:", width)
print("Channels:", channels)

# Print some pixel values
print("\nPixel at (0,0):", image[0,0])
print("Pixel at (50,50):", image[50,50])

# Print first 5x5 pixel values
print("\nFirst 5x5 Pixel Values:")
print(image[0:5, 0:5])

# Separate channels
blue = image[:, :, 0]
green = image[:, :, 1]
red = image[:, :, 2]

print("\nBlue Channel:")
print(blue)

print("\nGreen Channel:")
print(green)

print("\nRed Channel:")
print(red)


Image Shape: (3919, 5938, 3)
Height: 3919
Width: 5938
Channels: 3

Pixel at (0,0): [135  63   0]
Pixel at (50,50): [139  65   1]

First 5x5 Pixel Values:
[[[135  63   0]
  [135  63   0]
  [135  63   0]
  [135  63   0]
  [135  63   0]]

 [[135  63   0]
  [135  63   0]
  [135  63   0]
  [135  63   0]
  [135  63   0]]

 [[135  63   0]
  [135  63   0]
  [135  63   0]
  [135  63   0]
  [135  63   0]]

 [[135  63   0]
  [135  63   0]
  [135  63   0]
  [135  63   0]
  [135  63   0]]

 [[135  63   0]
  [135  63   0]
  [135  63   0]
  [135  63   0]
  [135  63   0]]]

Blue Channel:
[[135 135 135 ... 205 205 205]
 [135 135 135 ... 205 205 205]
 [135 135 135 ... 205 205 205]
 ...
 [ 34  34  34 ...   7   4   2]
 [ 34  34  34 ...   7   4   2]
 [ 33  33  33 ...   4   3   1]]

Green Channel:
[[ 63  63  63 ... 106 106 106]
 [ 63  63  63 ... 106 106 106]
 [ 63  63  63 ... 106 106 106]
 ...
 [ 19  19  19 ...   3   2   2]
 [ 19  19  19 ...   3   2   2]
 [ 18  18  18 ...   2   3   3]]

Red Channel:
[[ 0  0